language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

env: SYMFONY_VERSION=2.8.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source

matrix:
  allow_failures:
    - php: hhvm

notifications:
    email: whyte624@gmail.com
